### ISSUE TITLE
Разобраться, почему не генерируются нормально модели для списков

### ISSUE THREAD

**Issue by prt0117** [svetit-io/svetit#266]
![image](https://github.com/user-attachments/assets/48e495c9-2096-49c3-83ff-dc97e2bf6f06)

найдена проблема.
генератор не сгенерировал внутрянку модели UserInfos. 

при этом описание ручки:
```
get:
  summary: List of users
  operationId: handler-user-list-get
...
  parameters:
...
  responses:
    '200':
      $ref: ../components/responses/UserInfos.yaml
...
```
В этом респонсе у нас:
```
description: A paged array of projects
content:
  application/json:
    schema:
      $ref: ../schemas/UserInfos.yaml
```
В схеме $ref: ../schemas/UserInfos.yaml:
```
type: array
maxItems: 100
items:
  $ref: ./UserInfo.yaml
```

Схема для одной сущности UserInfo:
```
type: object
required:
  - displayName
  - login
  - firstname
  - lastname
  - email
properties:
  id:
    type: string
    format: uuid
    minLength: 36
    maxLength: 36
    pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
  displayName:
    type: string
    minLength: 1
  login:
    type: string
    minLength: 1
  firstname:
    type: string
    minLength: 1
  lastname:
    type: string
    minLength: 1
  email:
    type: string
    minLength: 1
```

То же самое для всех остальных множественных моделей - sections, translations и т.д.
